spring:
  profiles: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hong
    url: jdbc:mysql://localhost:3306/day?serverTimezone=Asia/Seoul

cloud:
  aws:
    region:
      static: ap-northeast-2 # AWS 리전 설정
    credentials:
      accessKey: AKIARM3PCPVY4MO62BEU # AWS access key, kosta 계정으로 수정 필요
      secretKey: UT1m5sDL+ZNk7smmdOjtO5mvLRyP9eYpxy/u26C7 # AWS secret key, kosta 계정으로 수정 필요
    s3:
      bucket: s3-moment # AWS bucket 설정, 수정 필요