spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qkznaks1!2!3!
    url: jdbc:mysql://54.180.201.152:3306/LAB?serverTimezone=Asia/Seoul
  thymeleaf:
    enabled: true
cloud:
  aws:
    s3:
      bucket: study-2022-08-02-1573058426
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA445KDIAQ3ZKB3QVW
      secretKey: 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
      use-default-aws-credentials-chain: false
      instance-profile: true
    stack:
      auto: false
email:
  account: moigae222@gmail.com
  password: beuxtqcyjxdatbub