spring:
  profiles: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        #dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1012
    url: jdbc:mysql://localhost:3306/pet?serverTimezone=Asia/Seoul
  thymeleaf:
    enabled: true
resource:
  handler: /admin/post/image/**
  location: file:///D:/imgUpload/

image:
  upload:
    path: D:\\imgUpload

cloud:
  aws:
    s3:
      bucket: study-2022-08-02-1573058426
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA445KDIAQ3ZKB3QVW
      secretKey: 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
      use-default-aws-credentials-chain: false
      instance-profile: true
    stack:
      auto: false
#cloud:
#  aws:
#    region:
#      static: ap-northeast-2 # AWS 리전 설정
#    credentials:
#      accessKey: AKIARM3PCPVY4MO62BEU # AWS access key, kosta 계정으로 수정 필요
#      secretKey: UT1m5sDL+ZNk7smmdOjtO5mvLRyP9eYpxy/u26C7 # AWS secret key, kosta 계정으로 수정 필요
#    s3:
#      bucket: s3-moment # AWS bucket 설정, 수정 필요